[package]
name = "geng-ui-derive"
version = "0.3.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Game Engine (ui derive macros)"
license = "MIT"
homepage = "https://github.com/kuviman/geng"
edition = "2018"

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
batbox = "0.3"
itertools = "0.9"
proc-macro2 = "1"

[lib]
proc-macro = true
