[package]
name = "geng-ecs-derive"
version = "0.9.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Game Engine (ecs derive macros)"
license = "MIT"
homepage = "https://github.com/kuviman/geng"
edition = "2021"

[dependencies]
syn = { version = "1", features = ["full", "visit-mut"] }
quote = "1"
proc-macro2 = "1"

[lib]
proc-macro = true
