[package]
name = "ugli-derive"
version = "0.11.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Universal OpenGL Interface (derive macros)"
license = "MIT"
homepage = "https://github.com/kuviman/ugli"
edition = "2021"

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
darling = "0.13"

[lib]
proc-macro = true
