[package]
name = "batbox"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]
edition = "2018"

[dependencies]
batbox-derive = { path = "derive" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ron = "0.5"
rand = "0.7"
log = "0.4"
threadpool = "1"
structopt = "0.3"
url = "2"
futures-preview = "0.3.0-alpha.17"
pin-utils = "0.1.0-alpha.4"
once_cell = "1"
bincode = "1"
objekt = "0.1"
maplit = "1"
stderrlog = "0.4"
backtrace = "0.3"
err-derive = "0.2"
trans = { git = "https://github.com/kuviman/trans-gen" }
trans-schema = { git = "https://github.com/kuviman/trans-gen" }

[target.'cfg(any(target_arch = "asmjs", target_arch = "wasm32"))'.dependencies]
stdweb = "0.4"

[target.'cfg(not(any(target_arch = "asmjs", target_arch = "wasm32")))'.dependencies]
libc = "0.2"
tinyfiledialogs = { git = "https://github.com/jdm/tinyfiledialogs-rs" }
