[package]
name = "batbox"
version = "0.7.0-alpha.1"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Batteries useful for projects"
license = "MIT"
homepage = "https://github.com/kuviman/batbox"
edition = "2018"

[dependencies]
batbox-derive = { path = "derive", version = "0.7.0-alpha" }
trans = "0.5.0-alpha"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
ron = "0.6"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
log = "0.4"
threadpool = "1"
structopt = "0.3"
url = "2"
futures = "0.3"
pin-utils = "0.1.0"
once_cell = "1"
bincode = "1"
dyn-clone = "1"
maplit = "1"
stderrlog = "0.5"
backtrace = "0.3"
thiserror = "1"
anyhow = "1"
async-trait = "0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2", features = [ "serde-serialize" ] }
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "Window",
    "Storage",
    "Navigator",
    "Location",
    "XmlHttpRequestResponseType",
    "ProgressEvent",
    "Document",
    "CssStyleDeclaration",
    "HtmlAudioElement",
    "XmlHttpRequest",
    "KeyboardEvent",
    "MouseEvent",
    "WheelEvent",
    "TouchEvent",
    "Touch",
    "TouchList",
    "DomRect",
    "DomRectReadOnly",
    "WebSocket",
    "BinaryType",
    "MessageEvent",
    "HtmlCanvasElement",
    "AngleInstancedArrays",
    "WebGlRenderingContext",
    "WebGlBuffer",
    "WebGlActiveInfo",
    "WebGlUniformLocation",
    "WebGlTexture",
    "WebGlRenderbuffer",
    "WebGlProgram",
    "WebGlFramebuffer",
    "WebGlShader",
    "HtmlImageElement",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libc = "0.2"
tinyfiledialogs = "3"
