[package]
name = "ugli"
version = "0.2.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Universal OpenGL Interface"
license = "MIT"
homepage = "https://github.com/kuviman/ugli"
edition = "2018"

[dependencies]
batbox = "0.2"
raw = { package = "ugli-raw", path = "raw", version = "0.1" }
ugli-derive = { path = "derive", version = "0.2" }
failure = "0.1"
num_enum = "0.4"

[target.'cfg(any(target_arch = "asmjs", target_arch = "wasm32"))'.dependencies]
stdweb = "0.4"

[target.'cfg(not(any(target_arch = "asmjs", target_arch = "wasm32")))'.dependencies]
image = "0.23"
glutin = "0.24"
