[package]
name = "geng"
version = "0.5.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Game Engine"
license = "MIT"
homepage = "https://github.com/kuviman/geng"
edition = "2018"

[dependencies]
geng-core = { path = "core", version = "0.5" }
geng-ui = { path = "ui", version = "0.5" }
geng-net = { path = "net", version = "0.5" }
geng-debug_overlay = { path = "debug_overlay", version = "0.5" }