[package]
name = "ugli"
version = "0.5.0-alpha.1"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Universal OpenGL Interface"
license = "MIT"
homepage = "https://github.com/kuviman/ugli"
edition = "2018"

[dependencies]
batbox = "0.5.0-alpha"
raw = { package = "ugli-raw", path = "raw", version = "0.5.0-alpha" }
ugli-derive = { path = "derive", version = "0.5.0-alpha" }
num_enum = "0.5"
serde = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = [
    "HtmlCanvasElement"
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
image = "0.23"
glutin = "0.24"
