[package]
name = "geng"
version = "0.8.0-alpha.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Game Engine"
license = "MIT"
homepage = "https://github.com/kuviman/geng"
edition = "2018"

[features]
default = ["audio"]
audio = ["rodio"]

[dependencies]
batbox = "0.7.0-alpha"
geng-derive = { path = "derive", version = "0.8.0-alpha" }
geng-ui-macros = { path = "ui-macros", version = "0.8.0-alpha" }
ugli = "0.7.0-alpha"
rusttype = { version = "0.9", features = [ "gpu_cache" ] }
serde = "1"
lazy_static = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
image = "0.23"
glutin = "0.26"
threadpool = "1"
num_cpus = "1"
notify = "4"
rodio = { version = "0.13", optional = true }
ws = { version = "0.9" }
