[package]
name = "ugli-derive"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
batbox = { git = "https://github.com/kuviman/batbox" }
proc-macro2 = "1"

[lib]
proc-macro = true
