[package]
name = "geng-derive"
version = "0.12.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Game Engine (derive macros)"
license = "MIT"
homepage = "https://github.com/kuviman/geng"
edition = "2021"

[dependencies]
batbox = { path = "../batbox", version = "0.12.0" }
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
darling = "0.14"

[lib]
proc-macro = true
