[package]
name = "ugli-webgl"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Universal OpenGL Interface (WebGL)"
license = "MIT"
homepage = "https://github.com/kuviman/ugli"
edition = "2018"

[build-dependencies]
webgl_generator = "0.2"

[dependencies]
stdweb = "0.4"
stdweb-derive = "0.5"
serde = "1"
serde_derive = "1"