[package]
name = "geng"
version = "0.12.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Game Engine"
license = "MIT"
homepage = "https://github.com/kuviman/geng"
edition = "2021"

[features]
default = ["audio"]
audio = ["rodio"]

[dependencies]
batbox = { path = "../batbox", version = "0.12.0" }
geng-ecs = { path = "../geng-ecs", version = "0.11.0" }
geng-derive = { path = "../geng-derive", version = "0.12.0" }
geng-ui-macros = { path = "../geng-ui-macros", version = "0.11.0" }
ugli = { path = "../ugli", version = "0.12.0" }
rusttype = { version = "0.9", features = [ "gpu_cache" ] }
serde = "1"
lazy_static = "1"
flate2 = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
image = "0.23"
glutin = "0.26"
threadpool = "1"
num_cpus = "1"
notify = "4"
rodio = { version = "0.13", optional = true }
ws = { version = "0.9" }
