[package]
name = "batbox-macros"
version = "0.9.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Batteries useful for projects (macros)"
license = "MIT"
homepage = "https://github.com/kuviman/batbox"
edition = "2021"