[package]
name = "geng-ecs"
version = "0.8.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Game Engine (ecs)"
license = "MIT"
homepage = "https://github.com/kuviman/geng"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng-ecs-derive = { path = "../geng-ecs-derive", version = "0.8.0" }
