[package]
name = "ugli-raw"
version = "0.9.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Universal OpenGL Interface (Raw)"
license = "MIT"
homepage = "https://github.com/kuviman/ugli"
edition = "2021"

[dependencies]
batbox = { path = "../batbox", version = "0.9.0" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gl = "0.14"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
