[package]
name = "ugli"
version = "0.11.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "Universal OpenGL Interface"
license = "MIT"
homepage = "https://github.com/kuviman/ugli"
edition = "2021"

[dependencies]
batbox = { path = "../batbox", version = "0.11.0" }
raw = { package = "ugli-raw", path = "../ugli-raw", version = "0.11.0" }
ugli-derive = { path = "../ugli-derive", version = "0.11.0" }
num_enum = "0.5"
serde = "1"
image = "0.23"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "0.26"
